### ISSUE TITLE
strfry not binding to port 7777

### ISSUE THREAD

**Issue by freQniK** [pluja/nerostr#7]
I have got the paywall set up and tested it with a change to the docker-compose.yml file for the rpc port of monero-wallet-rpc

However, if I don't add 

```
ports:
  - "127.0.0.1:7777:7777"
```

to the docker-compose.yml file in the `strfry-nerostr-relay:` section the strfry does not bind to port 7777. However, when I add this port to the docker-compose.yml file, I get "connection reset by peer" errors when testing the wss

Any advice would be greatly appreciated. Thanks you!

**Comment by pluja** [comment]
How are you configuring the relay? Are you using a reverse proxy?

**Comment by alaakaazaam** [comment]
In my case, the paywall is finally working : with the 'ports' attribute in strfry-nerostr-relay section, here is my nginx vhost file : 
```
    location / {
        proxy_pass http://localhost:8089;
    }
    location /strfry-nerostr-relay {
       proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://localhost:7777;
    }

```
I can see the '*Send 0.008 XMR or more ...' prompt with the qrcode associated

Good job !

**Comment by freQniK** [comment]
> How are you configuring the relay? Are you using a reverse proxy?

Hi! Thanks for following up. I finally got it to work! Like I mentioned before, strfry does not bind to port 7777 unless it is specified in the docker-compose.yml file. Here is my entire docker compose file:

```yaml
version: "3.9"

services:
  strfry-nerostr-relay:
    container_name: nerostr-strfry-relay
    image: pluja/nerostr-strfry:latest
    environment:
      - API_URL=http://nerostr:8080
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./nerostr_data/strfry/strfry-db:/app/strfry-db
    ports:
      - "127.0.0.1:7777:7777"


  monero-wallet-rpc:
    container_name: nerostr-monero-wallet-rpc
    env_file: 
      - .env
    image: sethsimmons/simple-monero-wallet-rpc:latest
    command: [
      "--wallet-file",
      "${MONERO_WALLET_FILENAME}",
      "--password",
      "${MONERO_WALLET_PASSWORD}",
      "--rpc-bind-port",
      "28081",
      "--daemon-host",
      "${MONERO_DAEMON_RPC_HOSTNAME}",
      "--daemon-port",
      "${MONERO_DAEMON_RPC_PORT}",
      "--disable-rpc-login",
      "--max-log-files",
      "1",
      "--max-log-file-size",
      "1000000"
    ]
    volumes:
      - ./nerostr_data/wallet/:/home/monero/wallet/
    ports:
      - "127.0.0.1:18081:28081"
    restart: unless-stopped

  nerostr:
    container_name: nerostr-paywall
    image: pluja/nerostr:latest
    env_file:
      - .env
    volumes:
      - ./nerostr_data/nerostr/nerostr-db:/app/nerostr_data/db
    ports:
      - "127.0.0.1:8089:8080"
    depends_on:
      - strfry-nerostr-relay
      - monero-wallet-rpc
 ```
 
 I could get the paywall working with nginx @alaakaazaam , but the websocket was having issues. I switched to caddy and websocketking (https://websocketking.com/) finally shows that it connects properly to the websocket. 
 
 Caddy is pretty sweet. It automatically pulled in my certbot SSL certificates. For completion, here is my `/etc/caddy/CaddyFile`
 
 ```
xmr.ithurtswhenip.ee {
        @websockets {
                header Connection *Upgrade*
                header Upgrade  websocket
        }
        encode zstd gzip

        reverse_proxy @websockets localhost:7777
        reverse_proxy localhost:8089
        header {
                Access-Control-Allow-Origin *
        }


}
```

Here is proof of my test post on the new XMR relay:

<img width="1202" alt="Screen Shot 2023-10-17 at 1 37 03 AM" src="https://github.com/pluja/nerostr/assets/93114223/1de139be-549e-4377-afce-e20a8e6d2793">
